--- # group var
haproxy_app_name: myapp
haproxy_mode: http
haproxy_enable_stats: enable 
haproxy_algorithm: roundrobin
haproxy_backend_servers:
  - {name: node01, ip: 192.168.56.101, port: 80, paramstring: cookie A check}
  - {name: node02, ip: 192.168.56.103, port: 80, paramstring: cookie A check}
haproxy_stats_users:
  - {username: haproxy, password: haproxy}

