--- # ElasticSearch setup
- name: Import GPG Key for ElasticSearch
  shell: rpm --import http://packages.elastic.co/GPG-KEY-elasticsearch
- name: Add ElasticSearch Repo
  template: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo
- name: Install ElasticSearch
  yum: name=elasticsearch state=latest
  notify: Restart ElasticSearch
